version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: romacopies-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - romacopies
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    container_name: romacopies-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-romacopies}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - romacopies
    command: --default-authentication-plugin=mysql_native_password

networks:
  romacopies:
    driver: bridge

volumes:
  dbdata:
  vendor_data:
